export enum ApiRoutes {
  LOGIN = "/api/login",
  SEARCH_STOCK = "/api/stocks/searchStocks",
  CAROUSELS = "/carousels",
}

export interface IBaseResponse<DataType> {
  code: number;
  data: DataType;
  msg: string;
  type: string;
}

// Generated by https://quicktype.io

export interface IPaginatedData<DataType> {
  total: number;
  per_page: number;
  current_page: number;
  last_page: number;
  data: DataType;
}
