// Generated by https://quicktype.io

export interface INewShare {
    id: number;
    mid: number;
    market: string;
    p_name: string;
    p_code: string;
    status: number;
    subscribe_price: string;
    subscribe_lottery_count: string;
    subscribe_count: number;
    quota_count: string;
    subscribe_amount: string;
    funded_amount: string;
    fee: string;
    is_order: number;
    created_at: number;
}
