// Generated by https://quicktype.io

export interface INews {
    uniquekey: string;
    title: string;
    date: string;
    category: string;
    author_name: string;
    url: string;
    thumbnail_pic_s?: string;
    is_content: string;
}

export interface IArticleDetails {
    uniquekey: string;
    detail: {
        title: string
        date: string;
        category: string;
        author_name: string;
        url: string;
        thumbnail_pic_s: string;
        thumbnail_pic_s02: string;
        thumbnail_pic_s03: string;
    }
    content: string;
}
